// API Response codes
export const API_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  OPENAI_API_ERROR: 'OPENAI_API_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

// Pagination defaults
export const PAGINATION_DEFAULTS = {
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

// Analysis settings
export const ANALYSIS_SETTINGS = {
  MAX_QUESTIONS: 6,
  MAX_DURATION_MINUTES: 15,
  MAX_TOKENS: 2000,
} as const;
